"Shooter colocado"
FRC5800/2022-RapidReact pull request #1
Opened 2022-02-06 20:00 UTC by Eduardo-Bocon

Coloquei o subsystem Shooter, mais os seus 2 commands e tambem com alterações no Robot Container e Constants.

2022-02-07 00:43 UTC, andrencs requested changes
Muito bom o desenvolvimento. Coloquei alguns comentários para estar alinhado com os demais da equipe.

2022-02-07 00:43 UTC, andrencs commented on 2022-RapidReact/src/main/java/frc/robot/commands/CommandShooter.java
> +public class CommandShooter extends CommandBase {
CommandShooter não deixa explicito o que esse command faz.

2022-02-07 00:43 UTC, andrencs commented on 2022-RapidReact/src/main/java/frc/robot/commands/CommandShooter.java
> +    timer.start();
se nao me engano o reset nao para a conteagem, apenas reinicia ela, dai nao precisa do start

2022-02-07 00:43 UTC, andrencs commented on 2022-RapidReact/src/main/java/frc/robot/RobotContainer.java
> +    final JoystickButton kB = new JoystickButton(m_joystick, 2);
esse número mágico aqui nao deveria estar no constants? Se nao me engano tem uma classe que ja tem os botões do controle mapeado, para não ter que remapear sempre.

2022-02-07 00:43 UTC, andrencs commented on 2022-RapidReact/src/main/java/frc/robot/commands/CommandShooter2.java
> +public class CommandShooter2 extends CommandBase {
Do mesmo modo que comentado anteriormente, commandShooter2 não deixa explícito o que esse command vai fazer

2022-02-07 00:43 UTC, andrencs commented on 2022-RapidReact/src/main/java/frc/robot/commands/CommandShooter2.java
> +    timer.start();
do mesmo modo como mencionado anteriormente, não sei se precisa desse start

2022-02-07 00:43 UTC, andrencs commented on 2022-RapidReact/src/main/java/frc/robot/commands/CommandShooter2.java
> +    return time > 1.5;
ao inves de criar mais uma variavel (time), não dava para usar o timer.get() aqui?

2022-02-07 00:43 UTC, andrencs commented on 2022-RapidReact/src/main/java/frc/robot/Constants.java
> +    public static int ShooterRightMotorShooterID = 4;
constantes nao deveriam ter o final na frente? E escritas em letras maiúsculas?

2022-02-07 00:43 UTC, andrencs commented on 2022-RapidReact/src/main/java/frc/robot/subsystems/Shooter.java
> +    rightMotor.set(-Constants.ShooterLowVelocity);
não entendi pq aqui usou as velocidades negativas.

2022-02-07 00:43 UTC, andrencs commented on 2022-RapidReact/src/main/java/frc/robot/subsystems/Shooter.java
> +
não precisa inverter nenhum motor?

2022-02-20 20:40 UTC, Nicolas-B-da-Costa approved these changes
Mudanças revisadas e código aprovado.

2022-02-23 12:47 UTC, ehne-al approved these changes

2022-02-24 00:26 UTC, andrencs requested changes

2022-02-24 00:26 UTC, andrencs commented on 2022-RapidReact/src/main/java/frc/robot/Main.java
> +    private Main() {
**do not modify this file**

2022-02-24 00:26 UTC, andrencs commented on 2022-RapidReact/src/main/java/frc/robot/Robot.java
> +    }
nesse arquivo tu nao fez absolutamente nada alem de colocar para o lado? sério?

2022-02-24 00:26 UTC, andrencs commented on 2022-RapidReact/src/main/java/frc/robot/RobotContainer.java
> +    private final XboxController m_joystick = new XboxController(0);
esse  numero magico nao é constante?

2022-02-24 00:26 UTC, andrencs commented on 2022-RapidReact/src/main/java/frc/robot/RobotContainer.java
> +        kB.whenPressed(new ShootWithShooter(shooter));
com que outra parte ele iria chutar se nao com o chutador?

2022-03-02 19:38 UTC, marcoacolla approved these changes

2022-03-02 20:09 UTC, msantosss approved these changes

2022-03-03 22:28 UTC, merged