Código do DriveTrain
FRC5800/2022-RapidReact pull request #2
Opened 2022-02-07 03:36 UTC by Nicolas-B-da-Costa

Esse é o código para o DriveTrain do robô, junto com o comando de inverter a frente enquanto um botão (x) estiver pressionado (além de haver os 4 TalonSRX e o giroscópio). Não consegui colocar o subsystem em maiúsculo (como o grupo havia combinado), por algum motivo. Acredito que algo estava mal posicionado quando tentei, mas agradeço se alguém conseguir editar isso para eu atualizar. As mudanças consistiram na criação do subsystem e dos 2 comandos (direção normal e invertida), além das configurações no RobotContainer e na adição dos IDs dos motores nas Constants, por questões de boas práticas. Há coisas que fiquei em dúvida se deveria botar em maiúsculo ou não, dito isso, estou à disposição para atualizar o código quando sugestões saírem.

2022-02-08 22:23 UTC, andrencs requested changes

2022-02-08 22:23 UTC, andrencs commented on 2022-RapidReact/src/main/java/frc/robot/RobotContainer.java
> +  private final DriveTrain cmd_drivetrain = new DriveTrain();
isso é um subsytem ou um comand? fiquei confuso com o cmd no meio da variavel.

2022-02-08 22:23 UTC, andrencs commented on 2022-RapidReact/src/main/java/frc/robot/RobotContainer.java
> +  private final XboxController xboxController = new XboxController(1);
esse numero magico nao deveria estar no constants?

2022-02-08 22:23 UTC, andrencs commented on 2022-RapidReact/src/main/java/frc/robot/RobotContainer.java
> +  private final JoystickButton xButton = new JoystickButton(xboxController, 3);
se nao me engano ja existe uma classe que mapeia os botoes do joystick, mas no caso de nao tiver, o 3 deveria estar no constants

2022-02-08 22:23 UTC, andrencs commented on 2022-RapidReact/src/main/java/frc/robot/RobotContainer.java
> +    xButton.whenHeld(new InvertDriver(cmd_drivetrain, xboxController));
acho que nao é uma boa ideia o piloto ter que ficar segurando o x enquanto manobra de re.

2022-02-08 22:23 UTC, andrencs commented on 2022-RapidReact/src/main/java/frc/robot/commands/InvertDriver.java
> +// Copyright (c) FIRST and other WPILib contributors.
sera que nao fica mais facil se inverter o sentido dos motores dentro do substismte ao inves de criar um novo command exatamente igual ao driveTrain, mudando apenas o parametro passado para o mDrivetrain.arcadeDrive(moveSpeed, rotateSpeed)?

2022-02-08 22:23 UTC, andrencs commented on 2022-RapidReact/src/main/java/frc/robot/subsystems/DriveTrain.java
> +    //leftSlave.follow(leftMaster);
não falta resetar os motores?

2022-02-11 19:49 UTC, marcoacolla commented on 2022-RapidReact/src/main/java/frc/robot/subsystems/DriveTrain.java
> +  public void arcadeDrive(double moveSpeed, double rotateSpeed){
porque tu só não coloca o controller como parâmetro e usa o controller.getRawAxis ou getY e getX no lugar do moveSpeed e do turnSpeed? Daí tu não precisa criar eles de novo nos comandos

2022-02-14 10:36 UTC, Nicolas-B-da-Costa commented on 2022-RapidReact/src/main/java/frc/robot/RobotContainer.java
> +  private final DriveTrain cmd_drivetrain = new DriveTrain();
> isso é um subsytem ou um comand? fiquei confuso com o cmd no meio da variavel.

Resolvi essa parte. O que acontece é que eu instanciei o DriveTrain no comando como "cmd_drivetrain" pra marcar que aquele DriveTrain tava sendo usado no comando, aí copiei a linha e colei no Robot Container pra poupar tempo. Vendo agora, a lógica não é muito boa, então só tirei o "cmd_" da nomenclatura (e apliquei o camelCase, que tava faltando). Acredito que só "driveTrain" deixe bem claro que é um subsystem, certo?

2022-02-14 10:36 UTC, Nicolas-B-da-Costa commented on 2022-RapidReact/src/main/java/frc/robot/RobotContainer.java
> +  private final XboxController xboxController = new XboxController(1);
Resolvido, passei pra lá.

2022-02-14 10:36 UTC, Nicolas-B-da-Costa commented on 2022-RapidReact/src/main/java/frc/robot/RobotContainer.java
> +  private final XboxController xboxController = new XboxController(1);
> esse numero magico nao deveria estar no constants?

Resolvido, passei pra lá.

2022-02-14 10:39 UTC, Nicolas-B-da-Costa commented on 2022-RapidReact/src/main/java/frc/robot/RobotContainer.java
> +  private final JoystickButton xButton = new JoystickButton(xboxController, 3);
> se nao me engano ja existe uma classe que mapeia os botoes do joystick, mas no caso de nao tiver, o 3 deveria estar no constants

Sim, pesquisei sobre ela e tirei umas dúvidas com outros membros pra entender como ela funciona. Deve-se usar, no parâmetro do ID, "XboxController.Button.kX.value"; neste caso, o "kX" serve para o botão X, é necessário ver o nome que a biblioteca usa para aplicar em outros botões (embora acredito que o VScode dê na sugestão). Fiz o teste e funcionou certinho, meus problemas pra achar ID de botão acabaram, muito obrigado pela sugestão.

2022-02-17 08:26 UTC, Nicolas-B-da-Costa commented on 2022-RapidReact/src/main/java/frc/robot/subsystems/DriveTrain.java
> +    //leftSlave.follow(leftMaster);
Feito.

2022-02-17 08:33 UTC, Nicolas-B-da-Costa commented on 2022-RapidReact/src/main/java/frc/robot/subsystems/DriveTrain.java
> +    //leftSlave.follow(leftMaster);
Feito.

2022-02-17 08:34 UTC, Nicolas-B-da-Costa commented on 2022-RapidReact/src/main/java/frc/robot/subsystems/DriveTrain.java
> +    //leftSlave.follow(leftMaster);
> não falta resetar os motores?

Feito.

2022-02-20 22:24 UTC, Nicolas-B-da-Costa commented on 2022-RapidReact/src/main/java/frc/robot/RobotContainer.java
> +    xButton.whenHeld(new InvertDriver(cmd_drivetrain, xboxController));
> acho que nao é uma boa ideia o piloto ter que ficar segurando o x enquanto manobra de re.

Problema resolvido, a inversão foi configurada para funcionar a partir do momento em que o botão é apertado (bem com o retorno ao estado normal).

2022-02-20 22:27 UTC, Nicolas-B-da-Costa commented on 2022-RapidReact/src/main/java/frc/robot/commands/InvertDriver.java
> +// Copyright (c) FIRST and other WPILib contributors.
> sera que nao fica mais facil se inverter o sentido dos motores dentro do substismte ao inves de criar um novo command exatamente igual ao driveTrain, mudando apenas o parametro passado para o mDrivetrain.arcadeDrive(moveSpeed, rotateSpeed)?

Deletei o InvertDriver, o código, agora, está funcionando com um comando só. A única coisa é que inverti o sentido no comando, alterando o parâmetro; já que, pelo que sei, fazer isso no subsystem iria requerer o "setInverted()", que inverteria eixos necessários no sentido normal.

2022-02-21 02:01 UTC, marcoacolla approved these changes

2022-02-21 17:29 UTC, Eduardo-Bocon commented on 2022-RapidReact/src/main/java/frc/robot/RobotContainer.java
> +    xButton.toggleWhenPressed(new DriveRobot(driveTrain, xboxController));
O problema de usar nesse caso o toggleWhenPressed() é que o piloto vai ter q apertar duas vezes o botão, acho melhor botar o whenPressed()

2022-02-21 17:34 UTC, Eduardo-Bocon commented on 2022-RapidReact/src/main/java/frc/robot/commands/DriveRobot.java
> +  public static boolean isInverted;
seria bom botar o isInverted = false, porque assim quando tu iniciar o robo é garantido que a driveTrain não vai estar invertida.

2022-02-22 05:53 UTC, Nicolas-B-da-Costa commented on 2022-RapidReact/src/main/java/frc/robot/RobotContainer.java
> +    xButton.toggleWhenPressed(new DriveRobot(driveTrain, xboxController));
> O problema de usar nesse caso o toggleWhenPressed() é que o piloto vai ter q apertar duas vezes o botão, acho melhor botar o whenPressed()

Na verdade, não é o caso. Esse seria sim um problema, mas setar o comando como default faz com que o comando não desative. Testei no simulador e deu certo.

2022-02-22 06:51 UTC, Nicolas-B-da-Costa commented on 2022-RapidReact/src/main/java/frc/robot/commands/DriveRobot.java
> +  public static boolean isInverted;
> seria bom botar o isInverted = false, porque assim quando tu iniciar o robo é garantido que a driveTrain não vai estar invertida.

Resolvido. Achei que isso iria impedir a troca entre modo invertido e normal de ocorrer direito, mas deu tudo certo. Obrigado pela sugestão.

2022-02-22 23:17 UTC, Eduardo-Bocon commented on 2022-RapidReact/src/main/java/frc/robot/RobotContainer.java
> +    xButton.toggleWhenPressed(new DriveRobot(driveTrain, xboxController));
Ah, se deu certo ta tudo bem então kkkk

2022-02-22 23:46 UTC, Eduardo-Bocon approved these changes

2022-02-23 12:49 UTC, ehne-al approved these changes

2022-02-24 00:15 UTC, andrencs requested changes

2022-02-24 00:15 UTC, andrencs commented on 2022-RapidReact/src/main/java/frc/robot/RobotContainer.java
> +    xButton.toggleWhenPressed(new DriveRobot(driveTrain, xboxController));
se esse ja é o comando default pra que atrelar ele a um botão?

2022-02-24 00:15 UTC, andrencs commented on 2022-RapidReact/src/main/java/frc/robot/commands/DriveRobot.java
> +    isInverted = !isInverted;
sempre que começar a partida o robo vai começar de ré?

2022-02-24 00:15 UTC, andrencs commented on 2022-RapidReact/src/main/java/frc/robot/commands/DriveRobot.java
> +  public static boolean isInverted = false;
quem tem que guardar o estado é o subsystem e nao o comando

2022-02-24 00:15 UTC, andrencs commented on 2022-RapidReact/src/main/java/frc/robot/subsystems/DriveTrain.java
> +  public void arcadeDrive(double moveSpeed, double rotateSpeed){
o controller deve estar no command e nao do subsystem, pq outros locais podem chamar esses metodos, e nao necessariamente vai vir com o controller

2022-02-24 04:00 UTC, Nicolas-B-da-Costa commented on 2022-RapidReact/src/main/java/frc/robot/RobotContainer.java
> +    xButton.toggleWhenPressed(new DriveRobot(driveTrain, xboxController));
> se esse ja é o comando default pra que atrelar ele a um botão?

Porque o botão serve para fazer com que a variável boolean isInverted reaja. Em teoria, ele faria isso desligando o comando e religando ele com a variável de valor diferente. No entanto, ao colocar o comando como default, eu impedi o desligamento. É o que o Eduardo mencionou ali em cima: em teoria, o toggleWhenPressed() geraria a necessidade de o botão ser apertado 2 vezes para a inversão ocorrer com sucesso, mas setar o comando como default impede isso e faz com que apertar uma vez baste (como deve ser).

2022-02-24 04:01 UTC, Nicolas-B-da-Costa commented on 2022-RapidReact/src/main/java/frc/robot/commands/DriveRobot.java
> +    isInverted = !isInverted;
> sempre que começar a partida o robo vai começar de ré?

Não mais, o Eduardo me alertou disso e eu programei a isInverted para sempre iniciar como false, impedindo que o robô comece invertido (e, se o simulador está correto, deu certo).

2022-02-25 06:17 UTC, Nicolas-B-da-Costa commented on 2022-RapidReact/src/main/java/frc/robot/commands/DriveRobot.java
> +  public static boolean isInverted = false;
> quem tem que guardar o estado é o subsystem e nao o comando

Resolvido, a boolean isInverted foi movida para o subsystem DriveTrain.

2022-03-02 19:38 UTC, marcoacolla approved these changes

2022-03-02 20:11 UTC, msantosss approved these changes

2022-03-03 22:25 UTC, merged