add_storage
FRC5800/2022-RapidReact pull request #3
Opened 2022-02-07 14:01 UTC by marcoacolla

adicionando constantes, susbsystems e comandos para o funcionamento do storage.
Nota: O controle não foi configurado no código com a finalidade de evitar conflitos, logo, terá de ser adicionado posteriormente...

2022-02-09 23:00 UTC, Eduardo-Bocon commented on 2022-RapidReact/src/main/java/frc/robot/RobotContainer.java
> +    convTrigger =  new JoystickButton(controller, XboxController.Button.kStart.value);
Eu botaria o nome do botão de kStart ou buttonStart

2022-02-09 23:05 UTC, Eduardo-Bocon commented on 2022-RapidReact/src/main/java/frc/robot/subsystems/StorageSystem.java
> +    storageConv = new VictorSP(Constants.storageConvID);
Acho que ficaria mais entendível se tu botasse o nome do motor como "motor" ou "storageMotor"

2022-02-09 23:09 UTC, Eduardo-Bocon commented on 2022-RapidReact/src/main/java/frc/robot/subsystems/StorageSystem.java
> +      storageConv.set(speed);
acredito que como a velocidade do storage não varia, tu poderia tirar esse argumento do activateStorage e deixar um valor fixo no constants

2022-02-09 23:14 UTC, Eduardo-Bocon commented on 2022-RapidReact/src/main/java/frc/robot/Constants.java
> +    public static int storageConvID = 0;
Constantes tem que ter o "static" e o "final", alem disso o nome tem que ser tudo com letras maiusculas

2022-02-09 23:17 UTC, Eduardo-Bocon commented on 2022-RapidReact/src/main/java/frc/robot/RobotContainer.java
> +    convTrigger.whenHeld(new ActivateConveyor(storageSystem, 1.0));
acho que segurar o botão não seja a melhor ideia, eu botaria um botão que quando tu aperta liga o storage e quando tu aperta de novo ele desliga o storage.

2022-02-10 14:12 UTC, ehne-al commented on 2022-RapidReact/src/main/java/frc/robot/RobotContainer.java
> +  private final JoystickButton convTrigger;
talvez seja mais padronizável se decidirmos um único nome (Storage ou Conveyor) para isso. Fica confuso se esse trigger ativa um motor do storage system mas se chama conv.

2022-02-11 19:22 UTC, Nicolas-B-da-Costa commented on 2022-RapidReact/src/main/java/frc/robot/commands/ActivateConveyor.java
> +    storageSystem = st;
Talvez, fique mais legível se o nome para o "st" for mais completo, acredito que seja difícil identificar o que ele faz se ele for visto no meio do código.

2022-02-11 19:26 UTC, Nicolas-B-da-Costa commented on 2022-RapidReact/src/main/java/frc/robot/subsystems/StorageSystem.java
> +    storageConv = new VictorSP(Constants.storageConvID);
Não sei se isso pode ser feito aqui sem ocasionar erros, mas acho que fica mais claro se o motor for declarado e iniciado na mesma linha. Quando vi esse trecho pela primeira vez, fiquei meio confuso.

2022-02-15 18:27 UTC, Eduardo-Bocon approved these changes
Não encontrei mais nenhum erro, gostei que tu botou o "toggleWhenPressed " no RobotContainer.

2022-02-20 20:44 UTC, Nicolas-B-da-Costa approved these changes
Ao meu ver, parece tudo certo. E as nomenclaturas estão bem mais claras agora.

2022-02-23 12:48 UTC, ehne-al approved these changes

2022-02-23 23:53 UTC, andrencs requested changes

2022-02-23 23:53 UTC, andrencs commented on 2022-RapidReact/src/main/java/frc/robot/RobotContainer.java
> +    kStart.toggleWhenPressed(new ActivateConveyor(storageSystem, Constants.STORAGE_SPEED));
tem certeza que essa é a melhor opção?toggleWhenPressed


toggleWhenActive/toggleWhenPressed
This binding toggles a command, scheduling it when a trigger changes from inactive to active (or a button is initially pressed), and canceling it under the same condition if the command is currently running. Note that while this functionality is supported, **_toggles are not a highly-recommended option for user control_**, as they require the driver to keep track of the robot state. The preferred method is to use two buttons; one to turn on and another to turn off. Using a StartEndCommand or a ConditionalCommand is a good way to specify the commands that you want to be want to be toggled between.

https://docs.wpilib.org/pt/stable/docs/software/commandbased/binding-commands-to-triggers.html#togglewhenactive-togglewhenpressed

2022-03-02 21:15 UTC, msantosss approved these changes

2022-03-03 22:21 UTC, merged