climber
FRC5800/2022-RapidReact pull request #4
Opened 2022-02-07 14:34 UTC by ehne-al

2 climber commands + 1 climber subsystem

2022-02-08 23:53 UTC, pcasotti requested changes

2022-02-08 23:53 UTC, pcasotti commented on 2022-RapidReact/src/main/java/frc/robot/Constants.java
> +  public static final XboxController controller = new XboxController(controllerID);
constants era pra ser com letra maiúscula e o XboxController era pra estar no RobotContainer, guarda só o ID aqui

2022-02-08 23:53 UTC, pcasotti commented on 2022-RapidReact/src/main/java/frc/robot/commands/ClimberExtend.java
> +  private Timer timerClimberExtend = new Timer();
poderia se chamar apenas "timer" ele existe somente dentro do ClimberExtend então não tem motivo para ter isso no nome

2022-02-09 23:25 UTC, Eduardo-Bocon commented on 2022-RapidReact/src/main/java/frc/robot/RobotContainer.java
> +    buttonLb.whenPressed(new ClimberRetract(climber, 0.5));
eu botaria essas velocidades do climber no constants

2022-02-10 14:02 UTC, ehne-al commented on 2022-RapidReact/src/main/java/frc/robot/Constants.java
> +  public static final XboxController controller = new XboxController(controllerID);
consertado

2022-02-10 14:02 UTC, ehne-al commented on 2022-RapidReact/src/main/java/frc/robot/commands/ClimberExtend.java
> +  private Timer timerClimberExtend = new Timer();
consertado

2022-02-10 14:02 UTC, ehne-al commented on 2022-RapidReact/src/main/java/frc/robot/RobotContainer.java
> +    buttonLb.whenPressed(new ClimberRetract(climber, 0.5));
consertado

2022-02-11 19:38 UTC, Nicolas-B-da-Costa commented on 2022-RapidReact/src/main/java/frc/robot/Constants.java
> +public static final int ControllerID = 0;
Se tratando de constantes, essas 3 (linha 21, 22 e 25) não deveriam estar em letra maiúscula, ao invés de camelCase?

2022-02-11 19:55 UTC, Nicolas-B-da-Costa commented on 2022-RapidReact/src/main/java/frc/robot/RobotContainer.java
> +  private final JoystickButton buttonLb = new JoystickButton(RobotContainer.controller, Constants.BUTTON_LB_ID);
O André tinha me dito que ele acredita haver uma classe que possa mapear os botões do controle; mas ainda to pesquisando sobre ela, então não sei exatamente como funciona.

2022-02-11 19:57 UTC, Nicolas-B-da-Costa commented on 2022-RapidReact/src/main/java/frc/robot/commands/ClimberExtend.java
> +    timer.start();
Pelo que me falaram, o "timer.start();" não é necessário após o reset, porque o reset não para a contagem, apenas reinicia ela.

2022-02-16 21:58 UTC, Eduardo-Bocon approved these changes

2022-02-23 23:04 UTC, pcasotti approved these changes

2022-02-23 23:28 UTC, andrencs requested changes

2022-02-23 23:28 UTC, andrencs commented on 2022-RapidReact/src/main/java/frc/robot/commands/ClimberExtend.java
> +// Copyright (c) FIRST and other WPILib contributors.
não dava para deixar genérico esse comando e usar tanto para estender quanto para retrair? muda literalmente uma linha

2022-02-23 23:28 UTC, andrencs commented on 2022-RapidReact/src/main/java/frc/robot/commands/PIDDriveStraight.java
> +  public PIDDriveStraight(DriveTrain df, double distance) {
não seria dt ao inves de df?

2022-02-23 23:28 UTC, andrencs commented on 2022-RapidReact/src/main/java/frc/robot/commands/PIDDriveStraight.java
> +    return driveTrain.getTrueDistance() > distance;
se a ideia do pid é ser preciso, pq nao usar um >=?

2022-02-23 23:28 UTC, andrencs commented on 2022-RapidReact/src/main/java/frc/robot/commands/PIDTurnAngle.java
> +    driveTrain = df;
pq df e nao dt?

2022-02-23 23:28 UTC, andrencs commented on 2022-RapidReact/src/main/java/frc/robot/commands/PIDTurnAngle.java
> +    driveTrain.resetEncoders();
pq nao usar o gyro que é o componente que mede angulo?

2022-02-23 23:28 UTC, andrencs commented on 2022-RapidReact/src/main/java/frc/robot/commands/PIDTurnAngle.java
> +    return driveTrain.gyro.getAngle() > angle;
sera que nao vale colocar um >=

2022-02-23 23:28 UTC, andrencs commented on 2022-RapidReact/src/main/java/frc/robot/commands/PIDDriveStraight.java
> +    return driveTrain.getTrueDistance() > distance;
e se a distancia for negativa?

2022-02-23 23:28 UTC, andrencs commented on 2022-RapidReact/src/main/java/frc/robot/commands/PIDTurnAngle.java
> +    return driveTrain.gyro.getAngle() > angle;
e se o angulo for negativo?

2022-02-23 23:28 UTC, andrencs commented on 2022-RapidReact/src/main/java/frc/robot/Constants.java
> +public  static final double DISTANCE_CONVERSION = WHEEL_CIRCUMFERENCE / CPR;
o nome da variavel nao deixa claro se converte de distancia para alguma coisa ou de alguma coisa para distancia

2022-02-23 23:28 UTC, andrencs commented on 2022-RapidReact/src/main/java/frc/robot/subsystems/DriveTrain.java
> +    public double getAutoTurn(double destination){
isso nao foi usado nenhuma vez

2022-02-23 23:28 UTC, andrencs commented on 2022-RapidReact/src/main/java/frc/robot/subsystems/DriveTrain.java
> +    public Encoder getLefEncoder(){
isso nao foi usado nenhuma vez

2022-02-23 23:28 UTC, andrencs commented on 2022-RapidReact/src/main/java/frc/robot/subsystems/DriveTrain.java
> +    public Encoder getRightEncoder(){
isso nao foi usado nenhuma vez

2022-02-23 23:28 UTC, andrencs commented on 2022-RapidReact/src/main/java/frc/robot/subsystems/ExampleSubsystem.java
>  public class ExampleSubsystem extends SubsystemBase {
esse arquivo pode deletar ne?

2022-02-26 05:28 UTC, Nicolas-B-da-Costa approved these changes
Ao que me pareça, tudo certo. Não notei nenhuma irregularidade que não tenha sido apontada.

2022-03-02 19:37 UTC, marcoacolla approved these changes

2022-03-02 21:16 UTC, msantosss approved these changes

2022-03-03 22:05 UTC, merged